# TASK #1: DEFINE SINGLE AND MULTI-DIMENSIONAL  NUMPY ARRAYS

In [1]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax 
import numpy as np 
# Let's define a one-dimensional array 
list_1 = [1,2,3,4,5]
list_1

[1, 2, 3, 4, 5]

In [2]:
# Let's create a numpy array from the list "my_list"
my_numpy_array = np.array(list_1)
my_numpy_array 

array([1, 2, 3, 4, 5])

In [3]:
type(my_numpy_array)

numpy.ndarray

In [4]:
# Multi-dimensional (Matrix definition) 
my_matrix = np.array([[1,2,3],[4,5,6]])
my_matrix

array([[1, 2, 3],
       [4, 5, 6]])

MINI CHALLENGE #1: 
- Write a code that creates the following 2x4 numpy array

```
[[3 7 9 3] 
[4 3 2 2]]
```

In [5]:
arr = np.array([[3,7,9,3],[4,3,2,2]])
arr

array([[3, 7, 9, 3],
       [4, 3, 2, 2]])

# TASK #2: LEVERAGE NUMPY BUILT-IN METHODS AND FUNCTIONS 

In [6]:
# "rand()" uniform distribution between 0 and 1
x = np.random.rand(20)
x


array([2.31720963e-01, 3.99496272e-01, 2.90116425e-01, 1.05571001e-01,
       1.17170951e-01, 6.95649802e-01, 4.48424101e-04, 3.39153705e-01,
       1.96410188e-02, 4.80466285e-01, 4.62652418e-01, 2.04562428e-01,
       4.15400564e-01, 2.17924719e-01, 1.89949396e-01, 6.43911914e-02,
       3.70148426e-01, 5.17184616e-01, 9.99044231e-01, 4.22262463e-01])

In [7]:
# you can create a matrix of random number as well
y = np.random.rand(3,3)
y


array([[0.248553  , 0.601871  , 0.45017669],
       [0.86354499, 0.2567649 , 0.28911233],
       [0.59159663, 0.45890283, 0.50522408]])

In [8]:
# "randint" is used to generate random integers between upper and lower bounds
z = np.random.randint(1,50)
z

46

In [9]:
# "randint" can be used to generate a certain number of random itegers as follows
x = np.random.randint(1,50,15)
x

array([41, 14, 27, 33, 33, 22, 17, 13, 26,  5, 11, 13, 23,  6, 36])

In [10]:
# np.arange creates an evenly spaced values within a given interval
z = np.arange(1,50)
z


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [11]:
# create a diagonal of ones and zeros everywhere else
x = np.eye(7)
x

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [12]:
# Matrix of ones
x = np.ones((7,7))
x

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [13]:
# Array of zeros
y = np.zeros(8)
y


array([0., 0., 0., 0., 0., 0., 0., 0.])

MINI CHALLENGE #2:
- Write a code that takes in a positive integer "x" from the user and creates a 1x10 array with random numbers ranging from 0 to "x"

In [14]:
x = input("Provide the value of x : ")
arr = np.random.randint(0,x,10)
arr

Provide the value of x : 16


array([12, 15,  6, 10, 11,  8, 10, 13, 11, 15])

# TASK #3: PERFORM MATHEMATICAL OPERATIONS IN NUMPY

In [15]:
# np.arange() returns an evenly spaced values within a given interval
x  = np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
y = np.arange(1,10)
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
# Add 2 numpy arrays together
sum = x + y
sum


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
square_x = x**2
square_x

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [19]:
sqrt = np.sqrt(square_x)
sqrt

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [20]:
x = np.exp(y)
x

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

MINI CHALLENGE #3:
- Given the X and Y values below, obtain the distance between them

```
X = [5, 7, 20]
Y = [9, 15, 4]
```

In [21]:
x = np.array([5,7,20])
y = np.array([9,15,4])
z = x - y
p = np.square(z)
square_distance = np.sum(p)
distance = np.sqrt(square_distance)
distance

18.33030277982336

# TASK #4: PERFORM ARRAYS SLICING AND INDEXING 

In [22]:
arr = np.array([3,5,6,2,5,8,20,50])
arr

array([ 3,  5,  6,  2,  5,  8, 20, 50])

In [23]:
# Access specific index from the numpy array
arr[0]

3

In [24]:
# Starting from the first index 0 up until and NOT including the last element
arr[0:len(arr)-1]

array([ 3,  5,  6,  2,  5,  8, 20])

In [25]:
# Broadcasting, altering several values in a numpy array at once
arr[0:4] = 7
arr

array([ 7,  7,  7,  7,  5,  8, 20, 50])

In [26]:
# Let's define a two dimensional numpy array
matrix = np.random.randint(1,10,(4,4))
matrix

array([[1, 1, 1, 7],
       [3, 5, 6, 2],
       [6, 9, 8, 1],
       [4, 3, 4, 8]])

In [27]:
# Get a row from a mtrix
matrix[-1]

array([4, 3, 4, 8])

In [28]:
# Get one element
matrix[0][2]

1

MINI CHALLENGE #4:
- In the following matrix, replace the last row with 0

```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```



In [29]:
x = np.array([[2,30,20,-2,-4],[3,4,40,-3,-2],[-3,4,-6,90,10],[25,45,34,22,12],[13,24,22,32,37]])
x
x[4] = 0
x

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

# TASK #5: PERFORM ELEMENTS SELECTION (CONDITIONAL)

In [30]:
matrix = np.random.randint(1,10,(5,5))
matrix


array([[2, 1, 7, 9, 3],
       [1, 2, 8, 5, 8],
       [1, 5, 8, 2, 3],
       [7, 1, 7, 8, 2],
       [8, 9, 5, 1, 7]])

In [31]:
new_matrix = matrix[matrix > 5]
new_matrix


array([7, 9, 8, 8, 8, 7, 7, 8, 8, 9, 7])

In [32]:
# Obtain odd elements only
new_matrix = matrix[matrix % 2 != 0]
new_matrix

array([1, 7, 9, 3, 1, 5, 1, 5, 3, 7, 1, 7, 9, 5, 1, 7])

MINI CHALLENGE #5:
- In the following matrix, replace negative elements by 0 and replace odd elements with -2


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [33]:
x = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])
x[x < 0] = 0
x[x % 2 != 0] = -2
x

array([[ 2, 30, 20,  0,  0],
       [-2,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [-2, -2, 34, 22, 12],
       [-2, 24, 22, 32, -2]])

# TASK #6: UNDERSTAND PANDAS FUNDAMENTALS

In [34]:
# Pandas is a data manipulation and analysis tool that is built on Numpy.
# Pandas uses a data structure known as DataFrame (think of it as Microsoft excel in Python). 
# DataFrames empower programmers to store and manipulate data in a tabular fashion (rows and columns).
# Series Vs. DataFrame? Series is considered a single column of a DataFrame.

In [1]:
import pandas as pd

In [2]:
# Let's define a two-dimensional Pandas DataFrame
# Note that you can create a pandas dataframe from a python dictionary
bank_client_df =pd.DataFrame({'Bank Client ID':[111,222,333,444],'Bank Client Name':
                              ['Saumya', 'Sita','Shyam', 'Khatushyam'],'Net Worth [$]':
                              [3500,4000,5000,7000],'Years with Bank':[3,5,7,9]})
bank_client_df

Bank Client ID Bank Client Name  Net Worth [$]  Years with Bank
0             111           Saumya           3500                3
1             222             Sita           4000                5
2             333            Shyam           5000                7
3             444       Khatushyam           7000                9

In [3]:
# Let's obtain the data type 
type(bank_client_df)


pandas.core.frame.DataFrame

In [38]:
# you can only view the first couple of rows using .head()
bank_client_df.head(2)



Bank Client ID Bank Client Name  Net Worth [$]  Years with Bank
0             111           Saumya           3500                3
1             222             Sita           4000                5

In [39]:
# you can only view the last couple of rows using .tail()
bank_client_df.tail(2)


Bank Client ID Bank Client Name  Net Worth [$]  Years with Bank
2             333            Shyam           5000                7
3             444       Khatushyam           7000                9

MINI CHALLENGE #6:
- A porfolio contains a collection of securities such as stocks, bonds and ETFs. Define a dataframe named 'portfolio_df' that holds 3 different stock ticker symbols, number of shares, and price per share (feel free to choose any stocks)
- Calculate the total value of the porfolio including all stocks

In [40]:
portfolio_df = pd.DataFrame({'Stock Ticker':['ABC', 'MNO', 'GHI'],'Number': [60,40,50],
                            'Price per share [$]':[2,5,7]})
stock_sum = portfolio_df['Number'] * portfolio_df['Price per share [$]']
total_value = stock_sum.sum()
total_value

670

# TASK #7: PANDAS WITH CSV AND HTML DATA

In [44]:
# Pandas is used to read a html file and store data in a DataFrame
retirement_df = pd.read_html('https://www.ssa.gov/oact/progdata/nra.html')

In [ ]:
!pip install lxml

In [ ]:
!python -m pip install --upgrade pip


In [45]:
retirement_df[0]

Year of birth  \
0                                      1937 and prior   
1                                                1938   
2                                                1939   
3                                                1940   
4                                                1941   
5                                                1942   
6                                             1943-54   
7                                                1955   
8                                                1956   
9                                                1957   
10                                               1958   
11                                               1959   
12                                     1960 and later   
13  Notes: 1. Persons born on January 1 of any yea...   

                                                  Age  
0                                                  65  
1                                     65 and 2 months  
2                                     65 and 4 months  
3                                     65 and 6 months  
4                                     65 and 8 months  
5                                    65 and 10 months  
6                                                  66  
7                                     66 and 2 months  
8                                     66 and 4 months  
9                                     66 and 6 months  
10                                    66 and 8 months  
11                                   66 and 10 months  
12                                                 67  
13  Notes: 1. Persons born on January 1 of any yea...

In [ ]:
# House price website was not working 

MINI CHALLENGE #7:
- Write a code that uses Pandas to read tabular US retirement data
- You can use data from here: https://www.ssa.gov/oact/progdata/nra.html 

In [47]:
retirement_df = pd.read_html('https://www.ssa.gov/oact/progdata/nra.html')
retirement_df[0]

Year of birth  \
0                                      1937 and prior   
1                                                1938   
2                                                1939   
3                                                1940   
4                                                1941   
5                                                1942   
6                                             1943-54   
7                                                1955   
8                                                1956   
9                                                1957   
10                                               1958   
11                                               1959   
12                                     1960 and later   
13  Notes: 1. Persons born on January 1 of any yea...   

                                                  Age  
0                                                  65  
1                                     65 and 2 months  
2                                     65 and 4 months  
3                                     65 and 6 months  
4                                     65 and 8 months  
5                                    65 and 10 months  
6                                                  66  
7                                     66 and 2 months  
8                                     66 and 4 months  
9                                     66 and 6 months  
10                                    66 and 8 months  
11                                   66 and 10 months  
12                                                 67  
13  Notes: 1. Persons born on January 1 of any yea...

# TASK #8: PANDAS OPERATIONS

In [7]:
# Let's define a dataframe as follows:
bank_client_df =pd.DataFrame({'Bank Client ID':[111,222,333,444],'Bank Client Name':
                              ['Saumya', 'Sita','Shyam', 'Khatushyam'],'Net Worth [$]':
                              [3500,4000,5000,7000],'Years with Bank':[3,5,7,9]})
bank_client_df

Bank Client ID Bank Client Name  Net Worth [$]  Years with Bank
0             111           Saumya           3500                3
1             222             Sita           4000                5
2             333            Shyam           5000                7
3             444       Khatushyam           7000                9

In [9]:
# Pick certain rows that satisfy a certain criteria
df_loyal = bank_client_df[bank_client_df['Years with Bank'] >= 5 ]
df_loyal


Bank Client ID Bank Client Name  Net Worth [$]  Years with Bank
1             222             Sita           4000                5
2             333            Shyam           5000                7
3             444       Khatushyam           7000                9

In [10]:
# Delete a column from a DataFrame
del bank_client_df['Bank Client Name']
bank_client_df


Bank Client ID  Net Worth [$]  Years with Bank
0             111           3500                3
1             222           4000                5
2             333           5000                7
3             444           7000                9

MINI CHALLENGE #8:
- Using "bank_client_df" DataFrame, leverage pandas operations to only select high networth individuals with minimum $5000 
- What is the combined networth for all customers with 5000+ networth?

In [17]:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
client_high_networth = bank_client_df[ bank_client_df['Net worth [$]'] >= 5000]
client_high_networth
total_networth = client_high_networth['Net worth [$]'].sum()
total_networth

39000

# TASK #9: PANDAS WITH FUNCTIONS

In [18]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [20]:
# Define a function that increases all clients networth (stocks) by a fixed value of 20% (for simplicity sake) 
def networth_update(balance):
    return balance * 1.2

In [21]:
# You can apply a function to the DataFrame 
bank_client_df['Net worth [$]'].apply(networth_update)

0     4200.0
1    34800.0
2    12000.0
3     2400.0
Name: Net worth [$], dtype: float64

In [22]:
bank_client_df['Bank Client Name'].apply(len)

0    6
1    5
2    5
3    4
Name: Bank Client Name, dtype: int64

MINI CHALLENGE #9:
- Define a function that triples the stock prices and adds $200
- Apply the function to the DataFrame
- Calculate the updated total networth of all clients combined

In [23]:
portfolio_df = pd.DataFrame({'Stock Ticker':['ABC', 'MNO', 'GHI'],'Number': [60,40,50],
                            'Price per share [$]':[2,5,7]})
portfolio_df


Stock Ticker  Number  Price per share [$]
0          ABC      60                    2
1          MNO      40                    5
2          GHI      50                    7

In [24]:
def price_update(stock_price):
    return stock_price * 3 + 200

In [33]:
portfolio_updated = portfolio_df['Price per share [$]'].apply(price_update)
portfolio_updated.sum()

642

# TASK #10: PERFORM SORTING AND ORDERING IN PANDAS

In [34]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [35]:
# You can sort the values in the dataframe according to number of years with bank
bank_client_df.sort_values(by = 'Years with bank')

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

In [36]:
# Note that nothing changed in memory! you have to make sure that inplace is set to True
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [37]:
# Set inplace = True to ensure that change has taken place in memory 
bank_client_df.sort_values(by = 'Years with bank', inplace = True)

In [38]:
# Note that now the change (ordering) took place 
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

# TASK #11: PERFORM CONCATENATING AND MERGING WITH PANDAS

In [ ]:
# Check this out: https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html

In [41]:
df1 = pd.DataFrame({'A':['A0','A1', 'A2','A3'],
                    'B':['B0','B1','B2','B3'],
                    'C':['C0','C1','C2','C3'],
                    'D':['D0','D1','D2','D3']},
                  index = [0,1,2,3])

In [42]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [47]:
df2 = pd.DataFrame({'A':['A4','A5','A6','A7'],
                    'B':['B4','B5','B6','B7'],
                    'C':['C4','C5','C6','C7'],
                    'D':['D4','D5','D6','D7']},
                  index = [4,5,6,7])

In [48]:
df2

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [49]:
df3 = pd.DataFrame({'A':['A8','A9','A10','A11'],
                    'B':['B8','B9','B10','B11'],
                    'C':['C8','C9','C10','C11'],
                    'D':['D8','D9','D10','D11']},
                  index = [8,9,10,11])

In [50]:
df3

A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [51]:
pd.concat([df1,df2,df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

# TASK #12: PROJECT AND CONCLUDING REMARKS

- Define a dataframe named 'Bank_df_1' that contains the first and last names for 5 bank clients with IDs = 1, 2, 3, 4, 5 
- Assume that the bank got 5 new clients, define another dataframe named 'Bank_df_2' that contains a new clients with IDs = 6, 7, 8, 9, 10
- Let's assume we obtained additional information (Annual Salary) about all our bank customers (10 customers) 
- Concatenate both 'bank_df_1' and 'bank_df_2' dataframes
- Merge client names and their newly added salary information using the 'Bank Client ID'
- Let's assume that you became a new client to the bank
- Define a new DataFrame that contains your information such as client ID (choose 11), first name, last name, and annual salary.
- Add this new dataframe to the original dataframe 'bank_df_all'.

In [59]:
Bank_df_1 = pd.DataFrame({'Bank Client ID':[1,2,3,4,5],'First Name': ['Kanad','Tigana','Yogesh','Shyam','Ram'],
                          'Last Name':['Das','Moges','Sinha','Kumar','Kumar']})
Bank_df_1

Bank Client ID First Name Last Name
0               1      Kanad       Das
1               2     Tigana     Moges
2               3     Yogesh     Sinha
3               4      Shyam     Kumar
4               5        Ram     Kumar

In [60]:
Bank_df_2 = pd.DataFrame({'Bank Client ID':[6,7,8,9,10],'First Name': ['Baban','Sona','Sresth','Srishyam','Heyram'],
                          'Last Name':['Das','Roy','Shukla','Khatu','jay']})
Bank_df_2

Bank Client ID First Name Last Name
0               6      Baban       Das
1               7       Sona       Roy
2               8     Sresth    Shukla
3               9   Srishyam     Khatu
4              10     Heyram       jay

In [63]:
bank_df_all = pd.concat([Bank_df_1,Bank_df_2])
bank_df_all

Bank Client ID First Name Last Name
0               1      Kanad       Das
1               2     Tigana     Moges
2               3     Yogesh     Sinha
3               4      Shyam     Kumar
4               5        Ram     Kumar
0               6      Baban       Das
1               7       Sona       Roy
2               8     Sresth    Shukla
3               9   Srishyam     Khatu
4              10     Heyram       jay

In [62]:
bank_df_salary = pd.DataFrame({ 'Bank Client ID':[1,2,3,4,5,6,7,8,9,10],
                    'Annual Salary':[10000,20000,30000,40000,50000,60000,32000,34000,54000,45000]})
bank_df_salary

Bank Client ID  Annual Salary
0               1          10000
1               2          20000
2               3          30000
3               4          40000
4               5          50000
5               6          60000
6               7          32000
7               8          34000
8               9          54000
9              10          45000

In [64]:
bank_df_all = pd.merge(bank_df_all, bank_df_salary, on = 'Bank Client ID')
bank_df_all


Bank Client ID First Name Last Name  Annual Salary
0               1      Kanad       Das          10000
1               2     Tigana     Moges          20000
2               3     Yogesh     Sinha          30000
3               4      Shyam     Kumar          40000
4               5        Ram     Kumar          50000
5               6      Baban       Das          60000
6               7       Sona       Roy          32000
7               8     Sresth    Shukla          34000
8               9   Srishyam     Khatu          54000
9              10     Heyram       jay          45000

In [65]:
New_Client_df = pd.DataFrame({'Bank Client ID': [11], 'First Name':['Saumya'],'Last Name':['Das'], 
                              'Annual Salary':[46000]})
New_Client_df

Bank Client ID First Name Last Name  Annual Salary
0              11     Saumya       Das          46000

In [66]:
pd.concat([bank_df_all,New_Client_df])

Bank Client ID First Name Last Name  Annual Salary
0               1      Kanad       Das          10000
1               2     Tigana     Moges          20000
2               3     Yogesh     Sinha          30000
3               4      Shyam     Kumar          40000
4               5        Ram     Kumar          50000
5               6      Baban       Das          60000
6               7       Sona       Roy          32000
7               8     Sresth    Shukla          34000
8               9   Srishyam     Khatu          54000
9              10     Heyram       jay          45000
0              11     Saumya       Das          46000

# MINI CHALLENGES SOLUTIONS

MINI CHALLENGE #1 SOLUTION: 
- Write a code that creates the following 2x4 numpy array

```
[[3 7 9 3] 
[4 3 2 2]]
```

In [ ]:
x = np.array([[[3, 7, 9, 3] , [4, 3, 2, 2]]])
x

MINI CHALLENGE #2 SOLUTION:
- Write a code that takes in a positive integer "x" from the user and creates a 1x10 array with random numbers ranging from 0 to "x"

In [ ]:
x = int(input("Please enter a positive integer value: "))
x = np.random.randint(1, x, 10)
x

MINI CHALLENGE #3 SOLUTION:
- Given the X and Y values below, obtain the distance between them


```
X = [5, 7, 20]
Y = [9, 15, 4]
```




In [ ]:
X = np.array([5, 7, 20])
Y = np.array([9, 15, 4])
Z = np.sqrt(X**2 + Y**2)
Z

MINI CHALLENGE #4 SOLUTION:
- In the following matrix, replace the last row with 0

```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```




In [ ]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])


In [ ]:
X[4] = 0
X

MINI CHALLENGE #5 SOLUTION:
- In the following matrix, replace negative elements by 0 and replace odd elements with -2


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```

In [ ]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

X[X<0] = 0
X[X%2==1] = -2
X

MINI CHALLENGE #6 SOLUTION:
- A porfolio contains a collection of securities such as stocks, bonds and ETFs. Define a dataframe named 'portfolio_df' that holds 3 different stock ticker symbols, number of shares, and price per share (feel free to choose any stocks)
- Calculate the total value of the porfolio including all stocks

In [ ]:
portfolio_df = pd.DataFrame({'stock ticker symbols':['AAPL', 'AMZN', 'T'],
                             'price per share [$]':[3500, 200, 40], 
                             'Number of stocks':[3, 4, 9]})
portfolio_df

In [ ]:
stocks_dollar_value = portfolio_df['price per share [$]'] * portfolio_df['Number of stocks']
print(stocks_dollar_value)
print('Total portfolio value = {}'.format(stocks_dollar_value.sum()))

MINI CHALLENGE #7 SOLUTION:
- Write a code that uses Pandas to read tabular US retirement data
- You can use data from here: https://www.ssa.gov/oact/progdata/nra.html 

In [ ]:
# Read tabular data using read_html
retirement_age_df = pd.read_html('https://www.ssa.gov/oact/progdata/nra.html')
retirement_age_df

MINI CHALLENGE #8 SOLUTION:
- Using "bank_client_df" DataFrame, leverage pandas operations to only select high networth individuals with minimum $5000 
- What is the combined networth for all customers with 5000+ networth?

In [ ]:
df_high_networth = bank_client_df[ (bank_client_df['Net worth [$]'] >= 5000) ]
df_high_networth

In [ ]:
df_high_networth['Net worth [$]'].sum()

MINI CHALLENGE #9 SOLUTION:
- Define a function that triples the stock prices and adds $200
- Apply the function to the DataFrame
- Calculate the updated total networth of all clients combined

In [30]:
def networth_update(balance):
    return balance * 3 + 200 

In [31]:
# You can apply a function to the DataFrame 
results = bank_client_df['Net worth [$]'].apply(networth_update)
results

0    10700
1    87200
2    30200
3     6200
Name: Net worth [$], dtype: int64

In [32]:
results.sum()

134300

PROJECT SOLUTION:

In [ ]:
# Creating a dataframe from a dictionary
# Let's define a dataframe with a list of bank clients with IDs = 1, 2, 3, 4, 5 

raw_data = {'Bank Client ID': ['1', '2', '3', '4', '5'],
            'First Name': ['Nancy', 'Alex', 'Shep', 'Max', 'Allen'], 
            'Last Name': ['Rob', 'Ali', 'George', 'Mitch', 'Steve']}

Bank_df_1 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_1


# Let's define another dataframe for a separate list of clients (IDs = 6, 7, 8, 9, 10)
raw_data = {
        'Bank Client ID': ['6', '7', '8', '9', '10'],
        'First Name': ['Bill', 'Dina', 'Sarah', 'Heather', 'Holly'], 
        'Last Name': ['Christian', 'Mo', 'Steve', 'Bob', 'Michelle']}
Bank_df_2 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_2


# Let's assume we obtained additional information (Annual Salary) about our bank customers 
# Note that data obtained is for all clients with IDs 1 to 10 
raw_data = {
        'Bank Client ID': ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
        'Annual Salary [$/year]': [25000, 35000, 45000, 48000, 49000, 32000, 33000, 34000, 23000, 22000]}
bank_df_salary = pd.DataFrame(raw_data, columns = ['Bank Client ID','Annual Salary [$/year]'])
bank_df_salary


# Let's concatenate both dataframes #1 and #2
# Note that we now have client IDs from 1 to 10
bank_df_all = pd.concat([Bank_df_1, Bank_df_2])
bank_df_all


# Let's merge all data on 'Bank Client ID'
bank_df_all = pd.merge(bank_df_all, bank_df_salary, on = 'Bank Client ID')
bank_df_all


In [ ]:
new_client = {
        'Bank Client ID': ['11'],
        'First Name': ['Ry'], 
        'Last Name': ['Aly'],
        'Annual Salary [$/year]' : [1000]}
new_client_df = pd.DataFrame(new_client, columns = ['Bank Client ID', 'First Name', 'Last Name', 'Annual Salary [$/year]'])
new_client_df

In [ ]:
new_df = pd.concat([bank_df_all, new_client_df], axis = 0)
new_df